opentracing-contrib/nginx-opentracing

opentracing/src/opentracing_request_instrumentor.cpp
opentracing/src/opentracing_request_instrumentor.h
opentracing/src/utility.cpp
opentracing/src/utility.h

Follows the same logic as NGINX's [$request_time](http://nginx.org/en/docs/http/ngx_http_log_module.html#var_request_time).

Use a more accurate method to determine endpoints on a request span.

---

docker/Dockerfile
jaeger/config
jaeger/config.make
jaeger/doc/Directives.md
jaeger/src/ngx_http_jaeger_module.cpp

Might need some fixing. Will update to jaegertracing/cpp-client as soon as pull request there is done.

Add Jaeger C++ client

---

jaeger/config
jaeger/src/ngx_http_jaeger_module.cpp

* Changes link order so that the dynamic opentracing library will be linked in instead of the static version that's compiled into jaeger.
* Adds logic to correctly set default values.
* Fixes type errors for configuration options.

Fix Jaeger module.

---

docker/Dockerfile
docker/README.md

Using Docker build arguments it's easy to build with the default values and also try with different branches or even `nginx` base images
https://github.com/opentracing-contrib/nginx-opentracing/issues/22

Use releases on the Dockerfile

---

doc/Directives.md
opentracing/src/ngx_http_opentracing_module.cpp
opentracing/src/opentracing_conf.h
opentracing/src/opentracing_request_instrumentor.cpp

It might be a security weakness to simply always trust and extract parent span information from all incoming requests. Depending on the way how NGINX is deployed the header in the request could be spoofed by clients or used to exploit vulnerabilities in the parser. I feel more comformtable exposing NGINX instances  which I know do not even *try* to parse user-supplied information that might be unsafe.

Add option to disable trusting incoming spans

---

opentracing/src/opentracing_request_instrumentor.cpp

The nginx  variable value can be changed at any phase of
the request. In such cases opentracing_operation_name
directive is not taking the latest value.
opentracing_operation_name directive is executed during
request init phase, so when its points to a variable X,
and if there is any update to X after init then the change
is not reflecting to opentracing_operation_name.
Testing:
Nginx Conf Details:
Declared the variable X in nginx conf and initialised it
to 'abcd'.Declared the opentracing_operation_name directive
and pointed it to $X
Case 1:
Updated the X to '1234' through other nginx modules (openresty)
Jaeger UI shows operation name for the request is 1234
Case 2:
No change to value of X Jaeger UI shows operation name for
the request is abcd

Add support for dynamic opentracing op name

---

opentracing/src/ngx_http_opentracing_module.cpp

Some tracing backends such as jaeger [don't support](https://github.com/jaegertracing/jaeger/issues/684) wildcard queries. This tag also is part of the multi-vendor opencensus tracing [http specification](https://github.com/census-instrumentation/opencensus-specs/blob/master/trace/HTTP.md#attributes) and makes it possible to query for traces by a specific vhost. Zipkin also [does not support](https://github.com/openzipkin/zipkin/issues/723) wildcard queries.

Add default `http.host` tag

---

zipkin/doc/Directives.md
zipkin/src/ngx_http_zipkin_module.cpp

This builds upon work in https://github.com/rnburn/zipkin-cpp-opentracing/pull/20 to provide probabilistic sampling when using zipkin.
* `zipkin_sample_rate` configuration option added. It should be a number between 0 and 1 and determines how likely a span is to be sampled.
* Sampling defaults to `1` (always sample) in the event of no incoming sampling decision.

Zipkin Sampling

---

example/trivial/jaeger/go/src/hello-backend/server.go
example/trivial/ubuntu-x86_64/go/src/hello-backend/server.go
example/trivial/zipkin/go/server.go

Modifies the trivial examples so that it returns the date instead of a fixed string.
Also, corrects some commenting.

Change examples to use date.

---

.circleci/config.yml
Dockerfile-openresty
ci/do_ci.sh
doc/Reference.md
example/lua/jaeger/docker-compose.yaml
example/lua/jaeger/jaeger-config.json
example/lua/jaeger/nginx.conf
example/lua/lightstep/docker-compose.yaml
example/lua/lightstep/lightstep-config.json.in
example/lua/lightstep/nginx.conf
example/lua/lightstep/start-nginx.sh
opentracing/src/opentracing_context.cpp
opentracing/src/opentracing_context.h
opentracing/src/opentracing_variable.cpp

This PR sets up the `opentracing/openresty` docker image that includes libraries to allow tracing Lua code. It also adds example for tracing Lua.

Adds an image and example for tracing OpenResty Lua code

---

opentracing/src/ngx_http_opentracing_module.cpp

If your nginx config doesn't have a http block (eg it's for a mail server), we get a null pointer crash when initialising the worker.
```
auto main_conf = static_cast<opentracing_main_conf_t *>(
ngx_http_cycle_get_module_main_conf(cycle, ngx_http_opentracing_module));
if (!main_conf->tracer_library.data) {
return NGX_OK;
}
```
```
#define ngx_http_cycle_get_module_main_conf(cycle, module)                    \
(cycle->conf_ctx[ngx_http_module.index] ?                                 \
((ngx_http_conf_ctx_t *) cycle->conf_ctx[ngx_http_module.index])      \
->main_conf[module.ctx_index]:                                    \
NULL)
```

Add check for missing HTTP block

---

opentracing/src/discover_span_context_keys.cpp
opentracing/src/ngx_http_opentracing_module.cpp

Restructure NGINX module linkage code to be similar to NGINX standards and best practices. This makes the code easier to understand. Remove typo.

Restructure Module Code With Best Practices

---

example/trivial/ubuntu-x86_64/Dockerfile-nginx

nginx couldn't be started because `1.14.1` was installed
```
nginx: [emerg] module "/etc/nginx/modules/ngx_http_opentracing_module.so" version 1014000 instead of 1014001 in /etc/nginx/nginx.conf:1
```
*  pin nginx version to `1.14.0`

Fix trivial ubuntu example

---

ci/build_module_binaries.sh

In a quest to increase the the range of pre-compiled binaries built via CI. 
I confirmed the versions translate to actually nginx releases define to [here](https://github.com/opentracing-contrib/nginx-opentracing/blob/master/ci/build_module_binary.sh#L7). 
[1.15.1](https://github.com/nginx/nginx/archive/release-1.15.1.tar.gz)
[1.13.6](https://github.com/nginx/nginx/archive/release-1.13.6.tar.gz)
Feedback welcome on PR or context provided. Thanks.

[ci] add nginx versions 1.15.1 and 1.13.6 to the list of versions to build

---

opentracing/src/ngx_http_opentracing_module.cpp

Subrequests begin their lives in the server-rewrite phase, so this
module is still loaded for subrequests.

Load module earlier, at server-rewrite phase. (#85)

---

.circleci/config.yml
ci/build_module_binaries.sh

[OpenResty's latest release](https://openresty.org/en/ann-1015008001.html) is based on `nginx-1.15.8`, so this is hopefully useful to others, too.
Resolves #100

Add nginx-1.15.8 to binaries list.

---

opentracing/src/ngx_http_opentracing_module.cpp
opentracing/src/request_tracing.cpp

When a request is redirected to an upstream, then it is not visible
where it went. The ngx_http_upstream module maintains a variable
"upstream_addr" for the resolved IP address + port information. It
also sets the name of the used upstream config entry to the request
as request->upstream->upstream->host.
So add that information to the new tags "upstream.address" and
"upstream.name".

Add upstream address and name tags

---

Dockerfile
opentracing/src/discover_span_context_keys.cpp

The change to `discover_span_context_keys.cpp` is to make sure the sampling priority is set before the context gets injected. The datadog tracer emits an error if sampling priority is changed after a span context has been injected.
Also bumping the version shipped in the docker image. Will try to be more proactive on bumping that in your project in the future.
Some recent users have been using the `opentracing/nginx-opentracing` container as a convenient, minimal sandbox, and these problems got reported.

Small fixups for datadog tracing

---

doc/Reference.md

We are referencing this page of the docs from [here](https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/opentracing.md#customize-opentracing) and some links in the doc were broken (maybe an old version of the API), so just updating the links with new links and naming so users can use the Doc properly.
Thanks

Update doc links about context propagation

---

ci/build_module_binaries.sh

Hi,
OpenResty [upgraded to `nginx` core 1.17.8 on July 4, 2020](https://openresty.org/en/changelog-1017008.html#version-11781---4-july-2020). I'm hoping this minor change will produce a compatible `nginx-opentracing` binary.

Add version 1.17.8

---

ci/build_module_binaries.sh

For compatibility with latest security fixes in Nginx releases, new builds of this module are desperately needed.

Add new nginx 1.19.x versions

---

Dockerfile-test
Makefile

Problem:
```
After this operation, 7848 kB of additional disk space will be used.
Ign:1 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libssl-dev amd64 1.1.1-1ubuntu2.1~18.04.7
Err:1 http://security.ubuntu.com/ubuntu bionic-updates/main amd64 libssl-dev amd64 1.1.1-1ubuntu2.1~18.04.7
404  Not Found [IP: 91.189.88.152 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl-dev_1.1.1-1ubuntu2.1~18.04.7_amd64.deb  404  Not Found [IP: 91.189.88.152 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command '/bin/sh -c apt-get install -y libssl-dev' returned a non-zero code: 100
```
Update Linux in test environment.
and make sure it works for latest nginx version.

Run system tests against nginx 1.19.7

---

Dockerfile
Dockerfile-openresty
Dockerfile-test

In the docker files use less git history during the building images.

Update Dockerfiles to use git clone depth

---

Dockerfile
example/go/otel/README.md
example/go/otel/docker-compose.yaml
example/go/otel/nginx.conf
example/go/otel/otel.yml
example/go/otel/zipkin-config.json

Zipkin cpp client supports Opentracing CPP v1.6.0 in https://github.com/rnburn/zipkin-cpp-opentracing/pull/48.
Update Dockerfile to build zipkin tracer.
Add nginx config to GO example for zipkin tracer to test integrations.

Support latest Zipkin tracer

---

example/trivial/jaeger/Dockerfile
example/trivial/ubuntu-x86_64/Dockerfile

FIxed build of examples. glide.sh is down

example: install glide with apt

---

opentracing/src/load_tracer.cpp

I noticed a typo in the error logging within `load_tracer`.  Here's a fix.

fix a copy/paste typo: too many format specifiers

---

example/go/otel/docker-compose.yaml

The docker image with nginx and opentracing has moved:
- https://hub.docker.com/r/opentracing/nginx-opentracing

QuickFix: Updating example to match Docker image location

---

.circleci/config.yml
.github/dependabot.yml
Dockerfile
ci/do_ci.sh

- Use multi-stage build to improve caching and avoid building if the version hasn't changed for a specific library
- Reduce size of final image
- Added specific version of NGINX that can be updated automatically with dependabot when a new version comes out

Convert Dockerfile to multi-stage build

---

Dockerfile

- Cross-compile libraries leveraging helper tools from https://github.com/tonistiigi/xx
- Remove gRPC build (doesn't seem to be used)
- Build plugin directly for zipkin, jaeger and datadog
- Avoid building unnecessary files for jaeger

Cross-compile libraries

---

Dockerfile

The docker image for latest changes has problem to run with opentracing module.
```shell
$ docker run -it opentracing/nginx-opentracing:edge nginx -g "load_module /usr/lib/nginx/modules/ngx_http_opentracing_module.so;"
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching …
```

Update links for shared libraries in Docker image

---

.github/release-drafter.yml
.github/workflows/release-drafter.yml

Add https://github.com/release-drafter/release-drafter to help with releases:
- It will automatically label PRs based on the branch name/keywords in the title/file modified.
- It will draft a new release with all the PRs since the last tag, categorizing them based on the applied label.

Add Release drafter and PR labeler

---

example/go/otel/docker-compose.yaml

Changed the example `docker-compose.yaml` to use
new docker image tag with master changes.
Also use stable version of opentelemetry collector.

Update go example to use latest master docker build

---

Dockerfile-openresty

- Updated OpenResty, LuaRocks and OpenSSL
- Fixed URLs for PCRE and LuaRocks

Update OpenResty to 3.19.9.1, fix PRCRE and LuaRocks URLs

---

.github/workflows/docker.yml

This will stop an "old" run of the workflow that is still not completed when there's a new push for the same branch/PR.
https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency

Cancel previously running jobs

---

Dockerfile

Update Jaeger to 0.9.0

---

README.md

The LIGHTSTEP_VERSION and ZIPKIN_CPP_VERSION build arguments were removed in https://github.com/opentracing-contrib/nginx-opentracing/pull/155/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557L6-L7. The NGINX_OPENTRACING_VERSION build argument was removed in https://github.com/opentracing-contrib/nginx-opentracing/pull/37/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557L10. This pr cleans up the list of build arguments available for use.
Worth noting: it looks like [Zipkin now supports OpenTracing 1.6.0](https://github.com/rnburn/zipkin-cpp-opentracing/blob/master/ci/build_plugin.sh#L12). Maybe we should add the Zipkin tracer back in to the docker image?

Clean up build argument list and add note on lightstep tracer

---

example/php/jaeger/Dockerfile
example/php/jaeger/composer.json

* The Composer version has changed, so the hash is no longer correct and it errors out on the build.
* Lacking the PHP zip extension, composer doesn't install other packages cleanly
* Moving to modern versions of the jaeger tracing library and opentracing implementation cleans up another error in the example

fix: Update to modern versions to get example working

---

.github/workflows/ci.yml

Build modules for NGINX 1.25.4

---

.github/workflows/docker.yml

Adds builds of all platforms on PRs. Also adds SBOMs (and SBOMs scanning) and Provenance.

Build Docker images for all platforms on PRs

---

Makefile
build/Dockerfile

Extracted the problem described in https://github.com/DataDog/dd-opentracing-cpp/pull/276#issuecomment-1954260078
We build docker images base on official nginx images (debian or alpine): https://github.com/opentracing-contrib/nginx-opentracing/blob/ee6c78630a09bad1dc27ca2c2a6a4acb3e8a3e16/Dockerfile#L244 
In same time we build bin modules for releasing using image ubuntu:2023 [build/Dockerfile](https://github.com/opentracing-contrib/nginx-opentracing/blob/master/build/Dockerfile#L1).
The problem that nginx images most of time would have older GLIBC version.
@dgoffredo wrote:
```
The latest release (v0.34.0) of nginx-opentracing is no longer compatible with nginx's debian-based docker images. nginx-opentracing v0.34.0 requires GLIBC 2.38, while e.g. nginx:1.25.4 has GLIBC 2.36:
```
* …

Build modules against same GLIBC as for official Nginx image

---

.github/workflows/ci.yml
Dockerfile

Add latest nginx version for build list: 1.25.5.
Fix Dockerfile build for Debian to use bookworm version and change the path for GPG key.

Build modules for NGINX 1.25.5

---

.github/workflows/docker.yml

In 0.35.0 release the broken tag created for Docker images.
Identified the problem with detecting nginx version.

Extract nginx version from Dockerfile argument

---

.github/workflows/docker.yml
.github/workflows/system-testing.yml
.github/workflows/update-docker-images.yml
Dockerfile
Makefile
build/Dockerfile

Fixes for dependabot and automated builds

---

Dockerfile

Updates Debian to 12, pins `clang` and `cmake` to latest version available

Bump base debian image to 12

---

Dockerfile

Restore building yaml-cpp

---

.github/workflows/ci.yml
Dockerfile

Builds modules for new nginx versions.
Also bumps the version in the Dockerfiles, because of https://github.com/dependabot/dependabot-core/issues/10452

Build modules for NGINX 1.27.1 and 1.26.2

---

.clang-format
.github/labeler.yml
.markdownlint-cli2.yaml
.pre-commit-config.yaml
.yamllint.yaml
README.md
doc/Reference.md
doc/Tutorial.md
example/go/otel/README.md
example/php/jaeger/README.md
example/trivial/datadog/README.md
example/trivial/jaeger/README.md
example/trivial/jaeger/go/src/hello-backend/glide.yaml
example/trivial/ubuntu-x86_64/README.md
example/trivial/ubuntu-x86_64/go/src/hello-backend/glide.yaml
example/trivial/zipkin/README.md
example/zoo/README.md
example/zoo/docker-compose.yaml

Updates the README and adds some badges. Updates all the files with new `yamllint` and `markdownlint` rules.

Update README and add more pre-commit checks
